### ISSUE TITLE
qnap install issues

### ISSUE THREAD

**Issue by travi** [travi/dotfiles#90]
- [x]
```sh
[~/dotfiles/setup] # . init.sh 
-sh: /root/.dotfiles/bash/colors.sh: No such file or directory

Linking dotfiles directory
  [ OK ] linked /root/dotfiles/setup/../ to /root/.dotfiles

Which setup step(s) would you like to perform?
	1: Environment configuration
	2: Software Installation/Update
	3: Both

Please enter your choice: 1

Link Dotfiles
BusyBox v1.01 (2015.05.21-18:58+0000) multi-call binary

Usage: find [PATH...] [EXPRESSION]

Search for files in a directory hierarchy.  The default PATH is
the current directory; default EXPRESSION is '-print'

EXPRESSION may consist of:
	-follow		Dereference symbolic links.
	-name PATTERN	File name (leading directories removed) matches PATTERN.
	-print		Print (default and assumed).

	-type X		Filetype matches X (where X is one of: f,d,l,b,c,...)
	-perm PERMS	Permissions match any of (+NNN); all of (-NNN);
			or exactly (NNN)
	-mtime TIME	Modified time is greater than (+N); less than (-N);
			or exactly (N) days


Improving Bash
  [ .. ] .bash_profile already exists
-sh: /root/.dotfiles/git/outstanding.sh: line 37: syntax error near unexpected token `<'
-sh: /root/.dotfiles/git/outstanding.sh: line 37: `    done <   <(find . -maxdepth 1 -mindepth 1 -type d -print0)'
```

**Comment by travi** [comment]
```sh
[admin@qnap:~]
[11:46:23] $ lla                                                                                                                                                                                                                             
ls: invalid option -- G
BusyBox v1.01 (2015.05.21-18:58+0000) multi-call binary

Usage: ls [-1AacCdeFilnpLRrSsTtuvwxXhk] [filenames...]

List directory contents

Options:
	-1	list files in a single column
	-A	do not list implied . and ..
	-a	do not hide entries starting with .
	-C	list entries by columns
	-c	with -l: show ctime
	-d	list directory entries instead of contents
	-e	list both full date and full time
	-F	append indicator (one of */=@|) to entries
	-i	list the i-node for each file
	-l	use a long listing format
	-n	list numeric UIDs and GIDs instead of names
	-p	append indicator (one of /=@|) to entries
	-L	list entries pointed to by symbolic links
	-R	list subdirectories recursively
	-r	sort the listing in reverse order
	-S	sort the listing by file size
	-s	list the size of each file, in blocks
	-T NUM	assume Tabstop every NUM columns
	-t	with -l: show modification time
	-u	with -l: show access time
	-v	sort the listing by version
	-w NUM	assume the terminal is NUM columns wide
	-x	list entries by lines instead of by columns
	-X	sort the listing by extension
	-h	print sizes in human readable format (e.g., 1K 243M 2G )
```

**Comment by travi** [comment]
reading the error above in more detail, it appears that the issue was not the looping method, but rather that `-mindepth 2 -maxdepth 2` and `-not -path` are not supported on the BusyBox version of `find`.

**Comment by travi** [comment]
installed `findutils` and added `/opt/bin/` to the front of the `$PATH` to give gnu `find precedence over BusyBox `find`

`ipkg install findutils`

**Comment by travi** [comment]
- [ ] 
```sh 
Error detected while processing /root/.vimrc:
line   32:
E484: Can't open file /usr/local/share/vim/syntax/syntax.vim
```

**Comment by travi** [comment]
fixed vim with:
* `ipkg install vim`
* `ln -s /share/CACHEDEV1_DATA/.qpkg/Optware/share/vim/syntax/syntax.vim syntax.vim`

**Comment by travi** [comment]
```
Failed to execute "python /root/dotfiles/vim/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py '/root/.bash_profile'". Exit code: 1
Message:
['Traceback (most recent call last):', '  File "/root/dotfiles/vim/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py", line 4, in <module>', '    from editorconfig.main import main', '  File "/root/dotfiles/vim/.vim/bundle/
editorconfig-vim/plugin/editorconfig-core-py/editorconfig/__init__.py", line 18, in <module>', '    from editorconfig.handler import EditorConfigHandler', '  File "/root/dotfiles/vim/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-p
y/editorconfig/handler.py", line 13, in <module>', '    from editorconfig.ini import EditorConfigParser', '  File "/root/dotfiles/vim/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/editorconfig/ini.py", line 22, in <module>', ' 
   from editorconfig.exceptions import ParsingError', '  File "/root/dotfiles/vim/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/editorconfig/exceptions.py", line 15, in <module>', '    from configparser import ParsingError as _
ParsingError', 'ImportError: No module named configparser']
```

**Comment by travi** [comment]
vim details on the qnap:
```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 18 2012 12:29:09)
Compiled by slug@imitron
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv -cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile -python 
-python3 +quickfix +reltime -rightleft -ruby +scrollbind +signs +smartindent 
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/share/vim"
Compilation: /home/slug/optware/ts509/toolchain/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H   -O2   -O2 -I/home/slug/optware/ts509/staging/opt/include   -O2   -O2 -I/home/slug/optware/ts509/staging/opt/include  -D_FORTIFY_SOURCE=1      
Linking: /home/slug/optware/ts509/toolchain/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-gcc   -L/home/slug/optware/ts509/staging/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,/home/slug/optware/ts509/staging/opt/lib -lncurses -o vim       -lm -L/home/slug/optware/ts509/staging/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,/home/slug/optware/ts509/staging/opt/lib -lncurses -ldl          
```

**Comment by travi** [comment]
Appears to be related to https://github.com/editorconfig/editorconfig-vim/issues/37 and confirmed that it does not happen with 7.4 on osx after updating to the latest version

osx vim details:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 30 2015 23:20:02)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.2.0 -lobjc -L/usr/local/Cellar/ruby/2.2.2/lib   
```

**Comment by travi** [comment]
windows vim details:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 17 2015 10:44:33)
MS-Windows 32-bit console version
Included patches: 1-638
Compiled by digitectNO@SPAMdancingpaper.com:http://SteveHallArchitecture.com
Big version without GUI.  Features included (+) or not (-):
+acl                +eval               +mouse              +syntax
+arabic             +ex_extra           -mouseshape         +tag_binary
+autocmd            +extra_search       +multi_byte_ime/dyn +tag_old_static
-balloon_eval       +farsi              +multi_lang         -tag_any_white
-browse             +file_in_path       -mzscheme           -tcl
++builtin_terms     +find_in_path       -netbeans_intg      -tgetent
+byte_offset        +float              +path_extra         -termresponse
+cindent            +folding            +perl/dyn           +textobjects
+clientserver       -footer             +persistent_undo    +title
+clipboard          +gettext/dyn        -postscript         -toolbar
+cmdline_compl      -hangul_input       +printer            +user_commands
+cmdline_hist       +iconv/dyn          -profile            +vertsplit
+cmdline_info       +insert_expand      +python/dyn         +virtualedit
+comments           +jumplist           +python3/dyn        +visual
+conceal            +keymap             +quickfix           +visualextra
+cryptv             +langmap            +reltime            +viminfo
+cscope             +libcall            +rightleft          +vreplace
+cursorbind         +linebreak          +ruby/dyn           +wildignore
+cursorshape        +lispindent         +scrollbind         +wildmenu
+dialog_con         +listcmds           +signs              +windows
+diff               +localmap           +smartindent        +writebackup
+digraphs           +lua/dyn            -sniff              -xfontset
-dnd                +menu               +startuptime        -xim
-ebcdic             +mksession          +statusline         -xterm_save
+emacs_tags         +modify_fname       -sun_workshop       -xpm_w32
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
Compilation: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -DHAVE_PATHDEF -DFEAT_BIG -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -w
-march=i386 -Wall -I/cygdrive/c/strawberry/perl/lib/Core -DFEAT_PERL -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby193/lib/ruby/1.9.1/i386-mingw32 -I /cygdrive/c/Ruby193/include/ruby-1.9.1 -I /cygdrive/c/Ruby193/include/ruby-1.9.1/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="msvcrt-ruby191.dll" -DDYNAMIC_RUBY_VER=191 -DFEAT_PYTHON  -DDYNAMIC_PYTHON -DFEAT_PYTHON3  -DDYNAMIC_PYTHON3  -O3 -fomit-frame-pointer -freg-struct-return -s
Linking: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -DHAVE_PATHDEF -DFEAT_BIG -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -w -march=i386 -Wall -I/cygdrive/c/strawberry/perl/lib/Core -DFEAT_PERL -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby193/lib/ruby/1.9.1/i386-mingw32 -I /cygdrive/c/Ruby193/include/ruby-1.9.1 -I /cygdrive/c/Ruby193/include/ruby-1.9.1/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="msvcrt-ruby191.dll" -DDYNAMIC_RUBY_VER=191 -DFEAT_PYTHON  -DDYNAMIC_PYTHON -DFEAT_PYTHON3  -DDYNAMIC_PYTHON3  -O3 -fomit-frame-pointer -freg-struct-return -s -mwindows -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -lole32 -luuid
```

**Comment by travi** [comment]
`ipkg install python` installed a version of python 2 that included `ConfigParser`, which  fixed the loading error for `editorconfig-vim`
